### ISSUE TITLE
Any reason behind making intention = 0 when sample_type = 'all'?

### ISSUE THREAD

**Issue by janismdhanbad** [ykotseruba/JAAD_dataset#11]
Hi,
Thanks a lot for this amazing work. I have recently started working with JAAD data and had confusion on this line(https://github.com/ykotseruba/JAAD/blob/a958453ef952c8a594bbd55dc630b531d0bb655e/jaad_data.py#L1292). Could you please let me know the reason behind making intention as 0 for all the pedestrians when the `sample_type = 'all'`. According to my understanding, there should still be pedestrians having an intention of 1, even is `sample_type='all'`. Please correct me if I am wrong.

Thanks!

**Comment by aras62** [comment]
Hi, 

Thank you for bringing that to our attention. The idea was that the intention of the samples that do not have behavioral labels should be set to 0  because they do not have crossing intention. This was, however, incorrectly implemented as you pointed out. We corrected the issue so only the ones without crossing intentions are set to 0.

**Comment by janismdhanbad** [comment]
Thank you so much for such a prompt response! :) The change makes complete sense to me. Just a follow-up question, should this(https://github.com/ykotseruba/JAAD/blob/4268bae2c0023a2b8ac631f4cb6946368e5c8535/jaad_data.py#L1259) line be also changed? As it is also being skipped if the sample_type='all'

**Comment by aras62** [comment]
Once again you are right. I changed that to check based on pedestrian id, not sequence type

**Comment by janismdhanbad** [comment]
Thanks for resolving my doubts. Really appreciate your quick responses. Looks all good now :100:
