### ISSUE TITLE
About pedestrian '0_5_12b'

### ISSUE THREAD

**Issue by xingchenzhang** [ykotseruba/JAAD_dataset#14]
Hi,

Many thanks for your great work!

I have some questions about the annotation of pedestrian '0_5_12b', could you please kindly help to clarify?

From video_0005_attributes.xml, I know 0_5_12b is a female adult (the lady with a child). 

In the video, this lady exists from frame 00000.png to 00158.png (**she is fully occluded by a car from frame 00159**). From around frame 00120.png she has occlusion.

However, in video_0005.xml, she exists from frame 12 to frame 206. Also, this file says she has occlusion from frame 12 to frame 77, and has no occlusion from frame 78 to 166, and then has part occlusion from frame 167 to frame 204.

So I think the image and annotations about '0_5_12_b' do not match. 

Furthermore, in your latest benchmark work that provides pose data, pedestrian 'o_5_12b' still has pose data from frame 00158.png to frame 00173.png, but actually she is fully occluded from frame 00159.png.

I am not sure if I made any mistake here...Could you please check if you have sometime? That would be very helpful!

Many thanks for your help!

Bests,
Xingchen

**Comment by ykotseruba** [comment]
Pedestrian `0_5_12b` is a man with a small girl in a pink coat. There was a mistake in the attributes which is now corrected. This should resolve your questions regarding the frame range for the pedestrian. 

In case there are other errors in the attributes, I suggest visualizing the data to establish the correspondences between the pedestrians and their labels. All annotations and videos can be viewed using [CVAT](https://github.com/openvinotoolkit/cvat). Version 0.3.0 is the one we used for the original annotations, I am not sure the XML files will work with the latest CVAT.

Poses were computed for all bounding boxes, even partially or fully occluded. Poses are likely not very good for those. In the benchmark occlusion was only present for a small percentage of the data since we only took the observation part, therefore we used it as is. You may want to experiment with filtering pose information by occlusion tag.

**Comment by xingchenzhang** [comment]
Hi Iuliia,

Many thanks for your reply and for correcting the attributes! That's very kind of you!

Also thanks a lot for your comments on the pose data in the benchmark since we are particularly interested in this.

By the way, can I ask have you performed normalization for the pose data? I have observed some pose data and found the range is between 0 and 1. So I am wondering this.

Thanks a lot again!

Bests,
Xingchen

**Comment by xingchenzhang** [comment]
Hi,

I have tried to use CVAT to visualise your annotations. The version I am using is the latest one I think (link is here https://cvat.org/tasks). However, the visualisation results and the annotation XML file do not match (not sure if this is related to the version of CVAT. I haven't successfully installed CVAT 0.3.0 yet).

The first problem is 'old_id' in the XML file is displayed instead of 'id'. For example, 'pedestrian' is displayed rather than '0_5_13b'.

The second problem is that, the displayed 'old_id' is not the same as that in the XML file. For example, the pedestrian '0_5_12b', its 'old_id' is pedestrian5, but in CVAT, 'PEDESTRIAN 7 (MANUAL)' is displayed. 

This inconsistency exists for many other pedestrians...I am not sure if this is related to the version of CVAT, and don't know if you have encountered similar issues previously.

Bests,
Xingchen

**Comment by ykotseruba** [comment]
I don’t recall having the issues you described with the latest cvat. Still, I do recommend using the older version in which the annotations were created.

**Comment by xingchenzhang** [comment]
OK, thank you very much for your quick reply!

I will try to install the older version again to see if that works.

Thanks!
Xingchen
