### ISSUE TITLE
annotations generation from .pkl file

### ISSUE THREAD

**Issue by wandyu** [ykotseruba/JAAD_dataset#17]

**Comment by wandyu** [comment]
Hello, I am trying to get some information (**bbox coordinates** and **pedestrian id's** with **occlusion, isGroup** and **isImportant**) from .pkl file to .xml file. I don't need the complete information like annotations in the annotations folder. I was able to extract the xml files with all the mentioned information except the **pedestrian ids**. Please help me to create the .xml file with specific information mentioned. Could you also please attach the file for converting the information from .pkl file dictionary to .xml annotation files?

**Comment by ykotseruba** [comment]
Hi,
All annotation files are in the xml format. Annotations are provided per video (e.g. see `annotations/video_0001.xml` for bounding boxes and `annotations_attributes/video_0001.xml` for all pedestrians in the first video ). These xml files are used to construct the `database.pkl`. So instead of using the database, you can parse the xml files directly. 
If you want to access pedestrian ids from the database, the structure of the database is explained in detail in the comments of `jaad_data.py` (see line 422). The keys of  the nested dictionary `database[video_id]['ped_annotations']` are pedestrian ids.

**Comment by abrams24** [comment]
Hi, I want to extract pedestrian trajectory files ('.pkl') like 0_1_3b.pkl, could you help/guide me on how to extract those data?

**Comment by jllliang** [comment]
> Hi, I want to extract pedestrian trajectory files ('.pkl') like 0_1_3b.pkl, could you help/guide me on how to extract those data?

hello, have you solved the problem?

**Comment by adibisoyi** [comment]
Hi @ykotseruba , For my model I need to extract pedestrian trajectory files as .pkl files (eg. 00131_0_109_608b.pkl). Can you help on how to generate the pickle files from the images extracted from the videos.
