### ISSUE TITLE
Pedestrian tracking error 

### ISSUE THREAD

**Issue by RodrigoGantier** [ykotseruba/JAAD_dataset#3]
In video number 102 there is a pedestrian crossing the street, but two pedestrians appear on the labels, so it is a tracking error, perhaps because it disappears and reappears in the scene (in the visible field of the camera)
PS: Labels on behavior data set are almost correct, change start_frame, from 134 to 137

**Comment by ykotseruba** [comment]
Hello Rodrigo,
as you noticed, the pedestrian goes out of frame and appears again, but the format of the vbb annotations does not allow to repeat labels. As a workaround we named this pedestrian as "pedestrian_p1" and "pedestrian_p2" so that we could still match the behavior data by "pedestrian" after removing the 'p1' and 'p2'.
It's not a tracking error really, rather the limitation of the annotation format that we chose to comply with the Caltech dataset standard. There are a few more cases where pedestrian track is interrupted in the JAAD dataset, maybe a total of 10 or so. All of them have a suffix 'p1', 'p2', etc.. I will update the readme to reflect this.
