### ISSUE TITLE
Calibration for camera available?

### ISSUE THREAD

**Issue by aranga81** [ykotseruba/JAAD_dataset#4]
Hi
Do you have intrinsic and extrinsic parameters available for all the cameras used for recording? if so can you share it ?

**Comment by ykotseruba** [comment]
Hello,
since our primary goal was pedestrian detection and behavior understanding, we do not have calibration information for the cameras. 
For the videos that are captured using GoPro Hero+ (videos 1-60), I believe you can use the calibration information for GoPro Hero3 White (which has the same hardware as Hero+):

Camera: GoPro Hero3 White (videos 1-60)
Mode: 1080p-30fps-wide
F = 1230 px
W = 1920 px
H = 1080 px
cx = 960 (lateral)
cy = 540 (vertical)
A = 1
k1 = -0.32
k2 = 0.126
t1 = 0
t2 = 0
k3 = 0

Unfortunately, we do not have access to the other two cameras that we used and they appear to be discontinued by the manufacturers. Here is all the information I could find online, perhaps it could be of use.
Camera: Highscreen Black Box Connect (videos 61-70)
f = 2.3 mm
Horizontal viewing angle 110 deg
Sensor 1/4’’
W = 1280 px
H = 720 px

Camera: Garmin GDR-35 (videos 71-346)
https://www.garmin.com.sg/products/discontinued/gdr35/#specsTab

**Comment by aranga81** [comment]
Hello
Thank you!
